# Generated by Django 4.0 on 2021-12-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucket',
            old_name='desc',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='bucket',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
