# Generated by Django 4.0 on 2021-12-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0002_rename_desc_bucket_description_alter_bucket_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='tags',
            field=models.ManyToManyField(to='bucket.Tag'),
        ),
    ]
