# Generated by Django 4.0 on 2021-12-23 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0003_bucket_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=120)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bucket.bucket')),
            ],
        ),
    ]
